### ISSUE TITLE
Consider using generate_release_notes

### ISSUE THREAD

**Issue by akaszynski** [pyansys/grantami-bomanalytics-openapi#61]
Consider using `generate_release_notes` as described in:
https://github.com/softprops/action-gh-release#-customizing

Apply it here:

https://github.com/pyansys/grantami-bomanalytics-openapi/blob/0109f659715739b7ae015ec20070c729d5ff0f93/.github/workflows/build_and_test_library.yml#L104-L107

Will be especially helpful for patch/minor releases.

**Comment by Andy-Grigg** [comment]
I don't think we'll need to use this for this repo, since it only contains generated code. Now we have all the workflows sorted, the commits from humans will only be to update the yml definition file.

This is useful for openapi-common and grantami-bomanalytics though, I'll create tickets there.

**Comment by da1910** [comment]
Agreed, we will likely want to document what changes between yaml versions, but that will be a manual process.
